name: AndroidBuild

on: workflow_dispatch

env:
  UNITY_VERSION: "2021.3.19f1"
  SUB_DIRECTORY: unity-auto-build-sample
  OUTPUT_PATH: Build

jobs:
  android-build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
        lfs: true
    - name: Search Path
      run: |
        echo $GITHUB_WORKSPACE
    - name: Build Android
      run: |
        /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath ./client/$SUB_DIRECTORY -executeMethod CI.BuildAndroid -buildTarget Android
