name: AndroidBuild

on: workflow_dispatch

env:
  UNITY_VERSION: "2021.3.19f1"
  SUB_DIRECTORY: unity-auto-build-sample
  OUTPUT_PATH: Build

jobs:
  android-build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
        lfs: true

    - name: Build Android
      run: |
        /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath ./$SUB_DIRECTORY -executeMethod CI.BuildAndroid -buildTarget Android

    - name: Upload DeployGate
      run: |
        curl \
          -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
          -F "file=@./$SUB_DIRECTORY/$OUTPUT_PATH/Android/Build.apk" \
          -F "distribution_name=${{secrets.DG_ANDROID_DIS_KEY}}" \
          -F "message=from github actions" \
          -v "https://deploygate.com/api/users/habu024/apps"
