name: iOSBuild

on: workflow_dispatch

env:
  UNITY_VERSION: "2021.3.19f1"
  SUB_DIRECTORY: unity-auto-build-sample
  PRODUCT_NAME: unity-auto-build-sample
  OUTPUT_PATH: Build

jobs:
  ios-build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
        lfs: true

    - name: Build iOS
      run: |
        /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath ./$SUB_DIRECTORY -executeMethod CI.BuildIOS -buildTarget iOS

    - name: Clean Xcode
      run: |
        xcodebuild clean -project ./$SUB_DIRECTORY/$OUTPUT_PATH/Xcode/Unity-iPhone.xcodeproj -target Unity-iPhone -configuration Release

    - name: Import Code Signing Certificates
      uses: apple-actions/import-codesign-certs@v1
      with:
        keychain: "signing_temp"
        create-keychain: true
        p12-file-base64: ${{secrets.BUILD_CERTIFICATE_BASE64}}
        p12-password: ${{secrets.P12_PASSWORD}}

    - name: Extract App Store Connect API Private Key
      env:
        ASC_API_KEY: ${{secrets.ASC_API_KEY}}
      run: |
        mkdir -p ./private_keys
        echo -n "$ASC_API_KEY" | base64 -d -o ./private_keys/AuthKey_${{secrets.ASC_KEY_ID}}.p8

    - name: Archive Xcode
      run: |
        xcodebuild \
          archive \
          -project ./$SUB_DIRECTORY/$OUTPUT_PATH/Xcode/Unity-iPhone.xcodeproj \
          -scheme Unity-iPhone \
          -archivePath ./$SUB_DIRECTORY/$OUTPUT_PATH/Xcode/Unity-iPhone.xcarchive \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
 
    - name: Build ipa
      env:
        ASC_ISSUER_ID: ${{secrets.ASC_ISSUER_ID}}
        ASC_KEY_ID: ${{secrets.ASC_KEY_ID}}
      run: |
        xcodebuild \
          -exportArchive \
          -archivePath ./$SUB_DIRECTORY/$OUTPUT_PATH/Xcode/Unity-iPhone.xcarchive \
          -exportPath ./$SUB_DIRECTORY/$OUTPUT_PATH/iOS \
          -exportOptionsPlist ./$SUB_DIRECTORY/$OUTPUT_PATH/iOS/ExportOptions.plist \
          -allowProvisioningUpdates \
          -authenticationKeyPath `pwd`/private_keys/AuthKey_${{secrets.ASC_KEY_ID}}.p8 \
          -authenticationKeyIssuerID $ASC_ISSUER_ID \
          -authenticationKeyID $ASC_KEY_ID

    - name: Upload DeployGate
      run: |
        curl \
          -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
          -F "file=@./$SUB_DIRECTORY/$OUTPUT_PATH/iOS/$PRODUCT_NAME.ipa" \
          -F "distribution_name=${{secrets.DEPLOYGATE_DISTRIBUTION_KEY}}" \
          -F "message=from github actions" \
          -v "https://deploygate.com/api/users/habu024/apps"

    - name: Clean up keychain and provisioning profile
      if: ${{always()}}
      run: |
        security delete-keychain signing_temp.keychain
