name: iOSBuild

on: workflow_dispatch

env:
  UNITY_VERSION: "2021.3.19f1"
  SUB_DIRECTORY: unity-auto-build-sample
  OUTPUT_PATH: Build

jobs:
  ios-build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        clean: false
        lfs: true
    - name: Build iOS
      run: |
        /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath ./$SUB_DIRECTORY -executeMethod CI.BuildIOS -buildTarget iOS
    - name: Clean Xcode
      run: |
        xcodebuild clean -project ./$SUB_DIRECTORY/$OUTPUT_PATH/Xcode/Unity-iPhone.xcodeproj -target Unity-iPhone -configuration Release
